name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.x'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: build-image
      if: github.ref == 'refs/heads/master'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      run: |
        set -e
        BOOT_VERSION=$(grep '<version>' pom.xml | head -n 1 | sed -e 's|<version>||g' -e 's|</version>||g' -e 's|<.*>||g' -e 's| ||g')
        set +e
        docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}        
        docker pull ${IMAGE_NAME}
        set -e
        ./mvnw -V spring-boot:build-image -DskipTests=true -Dspring-boot.version=${BOOT_VERSION} -Dspring-boot.build-image.imageName=${IMAGE_NAME}
        docker push ${IMAGE_NAME}
    # - uses: jvalkeal/setup-cf-cli@v0
    #   if: github.ref == 'refs/heads/master'
    #   with:
    #     version: 7.1.0
    # - name: cf push
    #   if: github.ref == 'refs/heads/master'
    #   env:
    #     CF_API: ${{ secrets.CF_API }}
    #     CF_USERNAME: ${{ secrets.CF_USERNAME }}
    #     CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
    #     CF_ORG: ${{ secrets.CF_ORG }}
    #     CF_SPACE: ${{ secrets.CF_SPACE }}
    #     IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
    #     SERVICE_BROKER_CLOUDAMQP_APIKEY: ${{ secrets.SERVICE_BROKER_CLOUDAMQP_APIKEY }}
    #   run: |
    #     set -e
    #     cf login -a ${CF_API} -u ${CF_USERNAME} -p ${CF_PASSWORD} -o ${CF_ORG} -s ${CF_SPACE}
    #     rm -f manifest.yml
    #     cf create-app cloudamqp-service-broker
    #     cf set-env cloudamqp-service-broker BPL_JVM_THREAD_COUNT 20
    #     cf set-env cloudamqp-service-broker JAVA_TOOL_OPTIONS "-XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo -Dspring.security.user.password=${SERVICE_BROKER_CLOUDAMQP_APIKEY} -Dservice-broker.cloudamqp.api-key=${SERVICE_BROKER_CLOUDAMQP_APIKEY}"
    #     cf push cloudamqp-service-broker -m 256m --strategy rolling -o ${IMAGE_NAME}